name: Implement
show: workflows
initialMessage: |
  Start the {workflowName} loop.

  Begin with Phase 1 ({firstPhaseName}).

  This is a looping workflow. You are intended to execute the phases in order, then loop until all the tasks are done.:
  1. "task-implementing": Implement 1-4 tasks in parallel
  2. `workflow_step next` -> "task-reviewing": Review the 1-4 tasks that were completed in step 1
  3. `workflow_step loop` -> "task-implementing": Fix issues found with the review
  4. `workflow_step next` -> "task-reviewing": Review the 1-4 tasks that were completed in step 1, reviewed in step 2, and fixed in step 3
  5. `workflow_step loop` -> "task-implementing": Implement 1-4 tasks in parallel
  6. ... etc
phases:
  - ../_rpir/task-implementing.md
  - ../_rpir/task-reviewing.md
